name: dependenoy

on:
  schedule:
    # 00:00 on every Sunday (UTC)
    - cron: "5 0 * * *"
    # - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - name: Check dependencies
        run: >
          ! deno run --allow-net --allow-read --allow-write
          https://deno.land/x/udd@0.5.0/main.ts --dry-run
          $(find . -name "*.ts") | grep -A 100 'Able to update'
