name: Update Assets
on:
  schedule:
    - cron: 0 0/6 * * *
  repository_dispatch:
    types: [update-assets]

# ref: https://github.com/technote-space/technote-space/blob/master/.github/workflows/update-stats.yml

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Download stats
        run: |
          curl -sS 'https://github-readme-stats.vercel.app/api?username=kawarimidoll&count_private=true&show_icons=true' \
          | sed 's/>/>\n/g' | sed 's/<!--.*-->//' | sed '/<!--/,/-->/d' | sed 's/  */ /g' \
          | tr -d '\n' > assets/stats.svg || echo 'Download stats: failed'
      - name: Download langs
        run: |
          curl -sS 'https://github-readme-stats.vercel.app/api/top-langs/?username=kawarimidoll&layout=compact' \
          | sed 's/>/>\n/g' | sed 's/<!--.*-->//' | sed '/<!--/,/-->/d' | sed 's/  */ /g' \
          | tr -d '\n' > assets/langs.svg || echo 'Download langs: failed'
      - name: Download trophies
        run: |
          curl -sS 'https://github-profile-trophy.vercel.app/?username=kawarimidoll&margin-w=5&no-frame=true' \
          | sed 's/>/>\n/g' | sed 's/<!--.*-->//' | sed '/<!--/,/-->/d' | sed 's/  */ /g' \
          | tr -d '\n' > assets/trophies.svg || echo 'Download trophies: failed'
      - name: Download streak
        run: |
          curl -sS 'https://github-readme-streak-stats.herokuapp.com/?user=kawarimidoll' \
          | sed 's/>/>\n/g' | sed 's/<!--.*-->//' | sed '/<!--/,/-->/d' | sed 's/  */ /g' \
          | tr -d '\n' > assets/streak.svg || echo 'Download streak: failed'
      - name: Download contribution-stats
        run: |
          curl -sS 'https://github-contribution-stats.vercel.app/api/?username=kawarimidoll' \
          | sed 's/>/>\n/g' | sed 's/<!--.*-->//' | sed '/<!--/,/-->/d' | sed 's/  */ /g' \
          | tr -d '\n' > assets/summary.svg || echo 'Download summary: failed'
      - name: Download header
        run: |
          curl -sS 'https://typograssy.vercel.app/api?text=Hello%20world!%20%E3%81%93%E3%82%93%E3%81%AB%E3%81%A1%E3%81%AF%E4%B8%96%E7%95%8C!%20&frame=none' \
          | sed 's/>/>\n/g' | sed 's/<!--.*-->//' | sed '/<!--/,/-->/d' | sed 's/  */ /g' \
          | tr -d '\n' > assets/header.svg || echo 'Download header: failed'

      - name: Git commit
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          if [ -n '$(git status --short || :)' ]
          then git commit -aqm 'update asssets' && git push origin
          else echo 'nothing to commit, working tree clean'
          fi
